CREATE TABLE cliente (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome       VARCHAR(255) NOT NULL,
    cliente_desde DATE NOT NULL
);

CREATE TABLE produto (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome    VARCHAR(255)   NOT NULL,
    preco   DECIMAL(10, 2) NOT NULL,
    estoque BOOLEAN        NOT NULL
);

CREATE TABLE pedido (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id BIGINT  NOT NULL,
    produto_id BIGINT  NOT NULL,
    quantidade INTEGER NOT NULL,
    CONSTRAINT fk_pedido_cliente FOREIGN KEY (cliente_id) REFERENCES cliente (id),
    CONSTRAINT fk_pedido_produto FOREIGN KEY (produto_id) REFERENCES produto (id)
);
